/** Flat, professional palette — no gradients */
export type ThemeColors = {
  bg: string;
  bgElevated: string;
  surface: string;
  card: string;
  cardSecondary: string;
  headerBg: string;
  headerText: string;
  textOnDark: string;
  textMuted: string;
  textOnCard: string;
  textMutedOnCard: string;
  primary: string;
  primaryLight: string;
  primarySoft: string;
  onPrimary: string;
  border: string;
  borderLight: string;
  divider: string;
  listRow: string;
  success: string;
  successSoft: string;
  warning: string;
  warningSoft: string;
  danger: string;
  dangerSoft: string;
  dangerDeep: string;
  sosPulse: string;
  tabInactive: string;
  tabActive: string;
  tabBar: string;
};

export const lightColors: ThemeColors = {
  bg: '#ECEFF2',
  bgElevated: '#FFFFFF',
  surface: '#FFFFFF',
  card: '#FFFFFF',
  cardSecondary: '#F7F8FA',
  headerBg: '#1A7B64',
  headerText: '#FFFFFF',
  textOnDark: '#111B21',
  textMuted: '#667781',
  textOnCard: '#111B21',
  textMutedOnCard: '#667781',
  primary: '#1A7B64',
  primaryLight: '#15856C',
  primarySoft: '#E7F5F1',
  onPrimary: '#FFFFFF',
  border: '#E9EDEF',
  borderLight: '#F0F2F5',
  divider: '#E9EDEF',
  listRow: '#FFFFFF',
  success: '#1A7B64',
  successSoft: '#E7F5F1',
  warning: '#B45309',
  warningSoft: '#FEF3C7',
  danger: '#DC2626',
  dangerSoft: '#FEE2E2',
  dangerDeep: '#991B1B',
  sosPulse: '#DC2626',
  tabInactive: '#667781',
  tabActive: '#1A7B64',
  tabBar: '#FFFFFF',
};

export const darkColors: ThemeColors = {
  bg: '#0B141A',
  bgElevated: '#1F2C34',
  surface: '#1F2C34',
  card: '#1F2C34',
  cardSecondary: '#182229',
  headerBg: '#1F2C34',
  headerText: '#E9EDEF',
  textOnDark: '#E9EDEF',
  textMuted: '#8696A0',
  textOnCard: '#E9EDEF',
  textMutedOnCard: '#8696A0',
  primary: '#22A082',
  primaryLight: '#2BB992',
  primarySoft: '#1A3D34',
  onPrimary: '#FFFFFF',
  border: '#2A3942',
  borderLight: '#233138',
  divider: '#2A3942',
  listRow: '#1F2C34',
  success: '#22A082',
  successSoft: '#1A3D34',
  warning: '#F59E0B',
  warningSoft: '#422006',
  danger: '#EF4444',
  dangerSoft: '#450A0A',
  dangerDeep: '#7F1D1D',
  sosPulse: '#EF4444',
  tabInactive: '#8696A0',
  tabActive: '#22A082',
  tabBar: '#1F2C34',
};
